image: mattgruter/drone
env:
  - PATH=${HOME}/.rbenv/versions/${RBENV_VERSION}/bin:$PATH
script:
  - sudo apt-get update
  - sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev libblkid-dev libcurl4-openssl-dev ruby libyaml-cpp-dev
  - cd ${DRONE_BUILD_DIR}
  - cmake .
  - make
  - make install
  - ls /usr/local/bin/
notify:
  email:
    recipients:
      - christj@gmail.com
