image: mattgruter/drone
env:
  - PATH=${HOME}/.rbenv/versions/${RBENV_VERSION}/bin:$PATH
script:
  - sudo apt-get update
  - sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev libblkid-dev libcurl4-openssl-dev ruby libyaml-cpp-dev
  - cd ${DRONE_BUILD_DIR}
  - cmake .
  - make
  - make install
  - /usr/local/bin/facter
  - echo hostname $HOSTNAME
  - echo hostcmd $(hostname)
  - test $(/usr/local/bin/facter hostname) == $(hostname)
notify:
  email:
    recipients:
      - christj@gmail.com
